# Generated by Django 5.2.2 on 2025-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(max_length=7)),
                ('update_rate_datatime', models.CharField(max_length=30)),
                ('request_datatime', models.CharField(max_length=30)),
            ],
        ),
    ]
